# Configuracion basica de la aplicacion
spring.application.name=user-service
server.port=8081

# Configuracion de la Base de Datos H2
spring.datasource.url=jdbc:h2:mem:users_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuracion de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Configuracion de Logs (SLF4J)
logging.level.root=INFO
logging.level.cl.duoc.fullstack.user_service=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%-5level] %logger{0} - %msg%n
