spring:
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:order_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

---
spring:
  config:
    activate:
      on-profile: render
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: ${PORT:8084}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    cl.duoc.fullstack.order_service_m4: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%-5level] %logger{0} - %msg%n"
  file:
    name: logs/order-service.log
