spring:
  application:
    name: cart-service
  profiles:
    active: h2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8080

logging:
  level:
    root: INFO
    cl.duoc.fullstack.cart_service_m3: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%-5level] %logger{0} - %msg%n"
  file:
    name: logs/cart-service.log
