spring:
  application:
    name: notification-service
  profiles:
    active: h2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8088

logging:
  level:
    root: INFO
    cl.duoc.fullstack.notification_service_m8: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%-5level] %logger{0} - %msg%n"
  file:
    name: logs/notification-service.log
