spring:
  application:
    name: payment-service
  profiles:
    active: h2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8085
  connection-timeout: 5000
  tomcat:
    connection-timeout: 5000
    keep-alive-timeout: 5000

logging:
  level:
    root: INFO
    cl.duoc.fullstack.payment_service_m5: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%-5level] %logger{0} - %msg%n"
  file:
    name: logs/payment-service.log
